name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    name: Lint and Type Check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"

      - name: Install uv
        run: pip install uv

      - name: Install dev dependencies
        run: uv sync --group dev

      - name: Run Ruff lint
        shell: pwsh
        run: uv run ruff check .

      - name: Run ruff ty check
        shell: pwsh
        run: uv run ty check .

      - name: Run isort check
        shell: pwsh
        run: uv run isort --check-only .

#      - name: Run mypy type check
#        shell: pwsh
#        run: uv run mypy src

  tests:
    runs-on: ubuntu-latest
    name: Test on Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        shell: pwsh
        run: uv run pytest tests --cov=VmaxBuilder --cov-report=xml --cov-report=term-missing -m "not integration and not usability"

      - name: Run integration tests
        shell: pwsh
        run: uv run pytest tests -m integration -v

      - name: Run usability tests
        shell: pwsh
        run: uv run pytest tests -m usability -v

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-py${{ matrix.python-version }}
